server:
  port: 9000

spring:
  application:
    name: 'authentication-service'
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/auth'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    jwt-secret: 'b0301262-ba1c-4ada-89f2-397df966b820'
    jwt-expiration-in-seconds: 86400
    jwt-refresh-token-expiration-in-seconds: 604800

logging:
  level:
    root: info